version: '2'
services:
  app:
    image: nalch/application:latest
    environment:
      - STAGE=p
    volumes:
      - nginx_html:/var/www/html
      - conf_path:/etc/local/application/conf
      - var_path:/var/local/application
    links:
      - postgres
    depends_on:
      - postgres
    networks:
      default: {}
      nginx-net: {}

  postgres:
    image: postgres:9
    environment:
      - POSTGRES_DB=application
      - POSTGRES_USER=application
      - POSTGRES_PASSWORD=application
      - PGDATA=/var/local/application/application/pgdata

volumes:
  app_path:
    external: true
  var_path:
    external: true
  nginx_html:
    external: true
  conf_html:
    external: true

networks:
  nginx-net:
    external:
      name: nginx-net