version: '2'
services:
  app:
    image: nalch/application:v1.0
    environment:
      - STAGE=p
    volumes:
      - nginx_html:/var/www/html
      - application_conf_path:/etc/local/application/conf
      - application_var_path:/var/local/application
    links:
      - postgres
    depends_on:
      - postgres
    networks:
      default: {}
      nginx-net: {}

  postgres:
    image: postgres:9
    environment:
      - POSTGRES_DB=application
      - POSTGRES_USER=application
      - POSTGRES_PASSWORD=application
      - PGDATA=/var/local/application/pgdata
    volumes:
      - application_var_path:/var/local/application

volumes:
  application_app_path:
    external: true
  application_var_path:
    external: true
  nginx_html:
    external: true
  application_conf_html:
    external: true

networks:
  nginx-net:
    external:
      name: nginx-net