version: '2'
services:
  app:
    build: .
    command: python /usr/src/app/manage.py runserver 0.0.0.0:8100
    ports:
      - "8500:8100"
    environment:
      - STAGE=dev
    volumes:
      - .:/usr/src/app
      - ./static:/var/www/html
      - ./config:/etc/local/application/conf
      - ./var:/var/local/application
    links:
      - postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:9
    environment:
      - POSTGRES_DB=application
      - POSTGRES_USER=application
      - POSTGRES_PASSWORD=application
      - PGDATA=/var/local/application/pgdata
    volumes:
      - ./var:/var/local/application